// src/app/components/shared/header.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-layout-header',
  templateUrl: './header.component.html',
  styles: [],
})
export class HeaderComponent implements OnInit {
  mounted = true;
  previousScroll = window.pageYOffset;

  ngOnInit(): void {
    window.onscroll = () => {
      const currentScroll = window.pageYOffset;
      this.mounted = this.previousScroll > currentScroll;
      this.previousScroll = currentScroll;
    };
  }
}

<header class="fixed z-20 w-full transition duration-500 ease-out transform-gpu bg-opacity-60 dark:bg-opacity-60 bg-white dark:bg-gray-900" [ngClass]="{'-translate-y-24': !mounted, 'shadow-xl backdrop-filter backdrop-blur-lg': !docked}">
  <div class="px-4 mx-auto max-w-screen-md w-auto py-4 md:py-6">
    <!-- Navigation links -->
    <nav class="flex items-center justify-between">
      <!-- Left -->
      <ul class="items-center space-x-6">
        <li>
          <a
            routerLink="/"
            class="transition-colors ease-in-out font-bold text-2xl tracking-wide text-gray-600 dark:text-gray-300 hover:text-pink-600 dark:hover:text-pink-500"
          >
            BRIAN LAI
          </a>
        </li>
      </ul>

      <!-- Right side -->
      <ul class="px-4 inline-flex items-center space-x-2">
        <li>
          <app-dark-toggle></app-dark-toggle>
        </li>
      </ul>
    </nav>
  </div>
</header>

// src/components/shared/Header.tsx
import { useState } from 'react'
import Link from 'next/link'
import { DarkToggle } from '@/components/shared'
import { useDocumentScrollThrottled } from '@/hooks'

const Header = () => {
  const [mounted, setMounted] = useState(false)
  const [docked, setDocked] = useState(false)

  const MINIMUM_SCROLL = 50
  const TIMEOUT_DELAY = 20

  useDocumentScrollThrottled(({ currentScrollTop, previousScrollTop }: any) => {
    const isScrolledDown = previousScrollTop < currentScrollTop
    const isMinimumScrolled = currentScrollTop > MINIMUM_SCROLL

    setDocked(currentScrollTop > 2)

    setTimeout(() => {
      setMounted(isScrolledDown && isMinimumScrolled)
    }, TIMEOUT_DELAY)
  })

  return (
    <header
      className={`${mounted ? '-translate-y-24' : ''} ${docked ? 'shadow-xl backdrop-filter backdrop-blur-lg' : ''} fixed z-20 w-full transition duration-500 ease-out transform-gpu bg-opacity-60 dark:bg-opacity-60 bg-white dark:bg-zinc-900`}
    >
      <div className="px-4 mx-auto max-w-screen-md w-auto py-4 md:py-6">
        {/* Navigation links */}
        <nav className="flex items-center justify-between">
          {/* Left */}
          <ul className="items-center space-x-6">
            <li>
              <Link href="/">
                <a className="font-bold text-2xl tracking-wide text-zinc-600 dark:text-zinc-300 hover:text-rose-600 dark:hover:text-rose-500">
                  BRIAN LAI
                </a>
              </Link>
            </li>
          </ul>
          {/* Right side */}
          <ul className="inline-flex items-center space-x-2">
            <li>
              <DarkToggle />
            </li>
          </ul>
        </nav>
      </div>
    </header>
  )
}

export default Header
