// src/components/shared/Footer.tsx
const Footer = () => {
  const year = new Date().getFullYear()

  return (
    <footer id="footer" className="container mx-auto mb-4 p-8">
      <div className="items-center justify-between text-center">
        <a
          id="footer-credits"
          href="https://github.com/blai30/blai30.github.io/"
          className="text-sm font-light text-zinc-600 dark:text-zinc-400 hover:text-rose-400 dark:hover:text-rose-400"
        >
          <span>Made by Brian with Next.js & Tailwind &copy; {year}</span>
        </a>
      </div>
    </footer>
  )
}

export default Footer

// src/app/components/shared/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-layout-footer',
  templateUrl: './footer.component.html',
  styles: []
})
export class FooterComponent {
  today: number = Date.now();
}

<footer class="container mx-auto mb-4 p-8">
  <div class="items-center justify-between text-center">
    <p class="text-sm font-light text-gray-600 dark:text-gray-500">
      <a
        id="footer-credits"
        href="https://github.com/blai30/blai30.github.io/"
        class="transition-colors ease-in-out hover:text-pink-400"
      >
        <span>Made by Brian with Angular & Tailwind &copy; {{today | date: 'yyyy'}}</span>
      </a>
    </p>
  </div>
</footer>
