// src/app/components/contact/contact.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html',
  styles: [],
})
export class ContactComponent {
}

<div class="mx-auto prose prose-pink md:prose-lg dark:prose-dark">
  <h2>Want to get in touch?</h2>
  <p>
    If you have any business inquiries, shoot me an email! I am open to all entry level software engineer opportunities. Feel free to connect with me on LinkedIn, download my resume, and explore all of my projects on GitHub.
  </p>
  <p>
    <span>Email: </span>
    <a
      id="contact-email"
      href="mailto:brianlai30@outlook.com"
      class="inline-flex items-center transition-colors ease-in-out no-underline"
    >
      <span>brianlai30@outlook.com</span>
    </a>
  </p>
  <p>
    <span>Resume: </span>
    <a
      id="contact-resume"
      href="https://blai30.github.io/resume/"
      class="inline-flex items-center transition-colors ease-in-out no-underline"
    >
      <span>https://www.bhlai.com/resume/</span>
    </a>
  </p>
  <p>
    <span>LinkedIn: </span>
    <a
      id="contact-linkedin"
      href="https://www.linkedin.com/in/blai/"
      class="inline-flex items-center transition-colors ease-in-out no-underline"
    >
      <span>https://www.linkedin.com/in/blai/</span>
    </a>
  </p>
  <p>
    <span>GitHub: </span>
    <a
      id="contact-github"
      href="https://github.com/blai30/"
      class="inline-flex items-center transition-colors ease-in-out no-underline"
    >
      <span>https://github.com/blai30/</span>
    </a>
  </p>
</div>

// src/components/Contact.tsx
const Contact = () => {
  return (
    <div className="mx-auto prose prose-pink md:prose-lg dark:prose-dark">
      <h2>Want to get in touch?</h2>
      <p>
        If you have any business inquiries, shoot me an email! I am open to all
        entry level software engineer opportunities. Feel free to connect with
        me on LinkedIn, download my resume, and explore all of my projects on
        GitHub.
      </p>
      <p>
        <span>Email: </span>
        <a
          id="contact-email"
          href="mailto:brianlai30@outlook.com"
          className="inline-flex items-center no-underline dark:text-pink-400 dark:hover:text-pink-300 transition-colors ease-in-out"
        >
          <span>brianlai30@outlook.com</span>
        </a>
      </p>
      <p>
        <span>Resume: </span>
        <a
          id="contact-resume"
          href="https://blai30.github.io/resume/"
          className="inline-flex items-center no-underline dark:text-pink-400 dark:hover:text-pink-300 transition-colors ease-in-out"
        >
          <span>https://blai30.github.io/resume/</span>
        </a>
      </p>
      <p>
        <span>LinkedIn: </span>
        <a
          id="contact-linkedin"
          href="https://www.linkedin.com/in/blai/"
          className="inline-flex items-center no-underline dark:text-pink-400 dark:hover:text-pink-300 transition-colors ease-in-out"
        >
          <span>https://www.linkedin.com/in/blai/</span>
        </a>
      </p>
      <p>
        <span>GitHub: </span>
        <a
          id="contact-github"
          href="https://github.com/blai30/"
          className="inline-flex items-center no-underline dark:text-pink-400 dark:hover:text-pink-300 transition-colors ease-in-out"
        >
          <span>https://github.com/blai30/</span>
        </a>
      </p>
    </div>
  )
}

export default Contact
